name: thirumathikart_app
description: A Flutter App for thirumathikart.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  get_storage: ^2.0.3
  smooth_page_indicator: ^1.0.0+2
  font_awesome_flutter: ^10.2.1
  lottie: ^1.4.2
  google_fonts: ^3.0.1 
  carousel_slider: ^4.1.1
  intl: ^0.17.0
  convert: ^3.0.2
  cached_network_image: ^3.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"

  flutter_lints: ^2.0.1

flutter_icons:
  image_path: "assets/tklogo.png"
  android: true 
  ios : true 

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/banner/
